<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '* 附薦包及功德狀只適用於<u><strong>同一</strong></u>表格登記之受薦先人，附送及額外附薦包類別(男/女/祖先)<u><strong>必須一致</strong></u>' => '',
    'Booking' => '服務登記',
    'Booking Name' => '服務登記名稱',
    'Create Level' => '新增級別',
    'Level' => '級別',
    'Registration Complete' => '登記完成',
    'Registration Confirmation' => '登記確認',
    'Template File' => '',
    '{qty,plural,=0{No quota} =1{Only one qouta} other{Only # quotas}} left.' => '只剩下 {qty} 個名額。',
    '不需要' => '',
    '個人聲明' => '',
    '功德狀' => '',
    '受薦先人姓名' => '',
    '受薦先人稱呼' => '',
    '受薦先人稱呼及姓名' => '@@@@',
    '只能包含 A-Z、a-z、0-9、-及_。' => '',
    '善信芳名' => '',
    '善信資料' => '',
    '善信電話' => '',
    '大號附薦包' => '',
    '女' => '',
    '尚餘名額：{0}' => '',
    '已滿額。' => '',
    '必需選擇 附薦位級別。' => '',
    '抱歉！暫未能預約。' => '',
    '新增服務登記表格' => '',
    '服務登記紀錄' => '',
    '服務登記表格' => '',
    '正號附薦包' => '',
    '申請完成時間' => '',
    '申請時間' => '',
    '申請確認時間' => '',
    '男' => '',
    '登記完成時間' => '@@@@',
    '登記日期' => '',
    '登記時間' => '',
    '登記確認時間' => '@@@@',
    '登記結束日期' => '',
    '登記編號' => '',
    '登記開始日期' => '',
    '祖先' => '',
    '籍貫(1)' => '',
    '籍貫(2)' => '',
    '網址' => '',
    '聯絡地區' => '',
    '聯絡地址' => '',
    '聯絡地址1' => '',
    '聯絡地址2' => '',
    '聯絡電郵' => '',
    '觀音開庫申請紀錄' => '',
    '附薦位級別' => '',
    '附薦位級別 未能預約。' => '',
    '附薦位級別價錢' => '',
    '附薦位認捐' => '',
    '附薦包及功德狀' => '',
    '附送正號附薦包／功德狀' => '',
    '陽居敬奉人姓名' => '',
    '需要' => '',
    '預約將於 {datetime} 開始。' => '',
    '預約已於 {datetime} 結束。' => '',
    '額外功德狀' => '',
    '額外功德狀價錢' => '',
    '額外大號附薦包' => '',
    '額外大號附薦包價錢' => '',
    '額外正號附薦包' => '',
    '（乙）善信資料' => '',
    '（甲）附薦位認捐' => '',
];
