<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>字數限制</strong><br/>中英文字：201<br/>純英文字：459' => '',
    'Add Recipients' => '加入接收者',
    'Address' => '',
    'All active members' => '全部生效的會員',
    'All active members with opt-in' => '全部生效的會員（願意個人資料作推廣用途）',
    'Cancel' => '取消',
    'Cancelled' => '取消',
    'Choose later' => '稍後選擇',
    'Content' => '內容',
    'Copy' => '複製',
    'Create EDM' => '新增EDM',
    'Done' => '完成',
    'EDM' => 'EDM',
    'EDM/SMS' => '',
    'Email' => '電郵',
    'Email Per Time' => '每次發送數量',
    'Failed' => '失敗',
    'Failed to resend.' => '重發失敗。',
    'Name' => '名稱',
    'Normal' => '正常',
    'Preview' => '預覽',
    'Recipient' => '接收者',
    'Recipients' => '接收者',
    'Resend' => '重發',
    'Resending.' => '重發中。',
    'SMS' => 'SMS',
    'Search' => '搜尋',
    'Send At' => '發送時間',
    'Sending' => '發送中',
    'Sent' => '@@已發出@@',
    'Sent At' => '發出時間',
    'Sent Response' => '',
    'Succeeded' => '成功',
    'Successfully Sent' => '成功發出',
    'Successfully to resend.' => '成功重發。',
    'Time Interval (Minute)' => '發送間距（分鐘）',
    'Title' => '標題',
    'Type' => '類型',
    'Waiting to send' => '等待發送',
];
