<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Credit Card Transaction Error! Please try again.' => '信用卡交易發生錯誤！請重試。',
    'Credit Card Transaction Failed! Please try again!' => '信用卡交易失敗！請重試。',
    'Error! Order not found. Please contact us.' => '發生錯誤！找不到你的訂單。請與我們聯絡。',
    'Error! Please try again.' => '發生錯誤！請重試。',
    'Payment Failed! Please try again!' => '',
    'Please contact us if you think this is an error. Thank you!' => '如果您認為這是錯誤的，請與我們聯繫。 謝謝！',
    'The above error occurred while the Web server was processing your request.' => '當我們處理您的請求時發生上述錯誤。',
    'These two passwords are not the same.' => '@@這兩個密碼並不相同。@@',
];
