<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ACT Code' => '',
    'ACT Name' => '',
    'CST Code' => '',
    'CST Name' => '',
    'Code' => '',
    'Created At' => '',
    'Delivery FAS Code' => '',
    'Download Xlsx' => '',
    'Error' => '',
    'FAS Code' => '',
    'FAS RI上載紀錄' => '',
    'Fas Transaction ID' => '',
    'Filename' => '',
    'ID' => '',
    'Is Generated' => '',
    'Is Uploaded' => '',
    'Is Xlsx Generated' => '',
    'Monthly Income Summay' => '',
    'Order ID' => '',
    'Order Num' => '',
    'Price' => '',
    'Product Code' => '',
    'Product Name' => '',
    'Qty' => '',
    'RI Receipt Number' => '',
    'RI上載紀錄' => '',
    'Record Num' => '',
    'Remark' => '',
    'Ren Act Code' => '',
    'Ren Analy Code' => '',
    'Ren Bk In' => '',
    'Ren Bk In Time' => '',
    'Ren Cq No' => '',
    'Ren Cramt' => '',
    'Ren Cst Code' => '',
    'Ren Desc' => '',
    'Ren No' => '',
    'Ren Payer Name' => '',
    'Ren Payer Refno' => '',
    'Ren Payment Mtd' => '',
    'Ren Ref No' => '',
    'Ren Ref Person' => '',
    'Ren Remark' => '',
    'Ren Replaced No' => '',
    'Ren Ri Created Time' => '',
    'Ren Status' => '',
    'Ren Time' => '',
    'Ren Type' => '',
    'Ren Void Reason' => '',
    'Ren Void Time' => '',
    'Service Name' => '',
    'Service Schedule Name' => '',
    'User Name' => '',
    'User Num' => '',
    'XML Date' => '',
];
