<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '({0})' => '@@（{0}）@@',
    '<b>Order Date:</b> {date}' => '<b>訂單日期︰</b>{date}',
    '<b>Order Notes:</b> {notes}' => '<b>訂單備註︰</b>{notes}',
    '<b>Order Number:</b> #{num}' => '<b>訂單編號︰</b>#{num}',
    '<b>Payment Method:</b> {method}' => '<b>付款方式︰</b>{method}',
    '<b>Shipping:</b> {shipping}' => '@@<b>運送費用︰</b>{shipping}@@',
    'Account registration at {0}' => '{0} 戶口登記',
    'BILLING ADDRESS' => '帳單地址',
    'Billing Address' => '帳單地址',
    'Dear {name}, ' => '你好，{name}！',
    'Email us: {email}' => '@@請電郵至 {email}@@',
    'Follow the link below to reset your password within 1 hour:' => '請於一小時內按以下連結重置您的密碼：',
    'Follow the link below to verify your email:' => '請按以下連結驗證您的戶口：',
    'Hello {0},' => '您好 {0}，',
    'Need assistance? Talk to us!' => '@@需要協助？歡迎與我們聯絡！@@',
    'ORDER' => '訂單',
    'ORDER DETAILS' => '訂單詳情',
    'Order Date: {date}' => '訂單日期︰{date}',
    'Order Details' => '訂單詳情',
    'Order Notes: {notes}' => '訂單備註︰{notes}',
    'Order Number: #{num}' => '訂單編號︰#{num}',
    'Password reset for {0}' => '{0} 的密碼重設',
    'Payment Method: {method}' => '付款方式︰{method}',
    'Product' => '產品',
    'QTY' => '數量',
    'SHIPPING' => '運費',
    'SHIPPING ADDRESS' => '送貨地址',
    'Shipping Address' => '送貨地址',
    'Shipping:' => '運費：',
    'Shipping: {shipping}' => '@@運送費用︰{shipping}@@',
    'TOTAL' => '合共',
    'The items you ordered will be processed as soon as possible.
See you again soon!' => '我們將儘快處理你的訂單。
期待你的再次光臨！',
    'The items you ordered will be processed as soon as possible.<br />See you again soon!' => '我們將儘快處理你的訂單。<br />期待你的再次光臨！',
    'Total' => '合共',
    'Total:' => '合共：',
    'We just got your order. Thank You!' => '你的訂單我們收到了，謝謝！',
    'We\'re pleased to tell you that the following items you ordered were recently shipped.' => '我們很高興通知你，你以下所訂購的物品已經發貨。',
    'We\'re pleased to tell you that your order status has been updated to {status}.' => '我們很高興通知你，您的訂單狀態已更新為 {status}。',
    '{site_name} - Order Confirmation (#{num})' => '{site_name} - 確認訂單（#{num}）',
    '{site_name} - Order Updated (#{num})' => '{site_name} - 訂單資訊（#{num}）',
    '{site_name} - Shipment Confirmation (#{num})' => '{site_name} - 確認送貨（#{num}）',
];
