<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply' => '申請',
    'Blessing Card' => '祈福卡',
    'Blessing Message' => '祈福字句',
    'Blessing Message Font Size' => '祈福字句文字大小',
    'Blessing Message Text Orientation' => '祈福字句方向',
    'Cannot apply Treasury Opening more than {qty}.' => '',
    'Create Service' => '新增服務',
    'Create Service Schedule' => '新增服務日程',
    'Create Services Group' => '新增服務組合',
    'Create Temple' => '新增廟宇',
    'Date' => '日期',
    'Date of Application' => '申請日期',
    'Default Qty' => '預設數量',
    'Download' => '',
    'Download Blessing Card' => '下載祈福卡',
    'Duplicate record number setting.' => '重複的紀錄編號設定',
    'Full' => '@@額滿@@',
    'Horizontal' => '橫行',
    'Large' => '大',
    'Maximin Number Of Periods Per Order' => '每次訂單最多購買期數',
    'Message Card Config' => '字句卡設定',
    'Middle' => '中',
    'No.' => '編號',
    'Number Of Periods' => '佔期數',
    'Period For Record Number' => '紀錄編號的期數',
    'Please input Name, Zodiac and Address District' => '@@請輸入姓名、生肖及住址地區@@',
    'Price' => '價錢',
    'Qty' => '',
    'Record Completed Time' => '紀錄完成時間',
    'Record Confirmed Time' => '紀錄確認時間',
    'Record Num' => '紀錄編號',
    'Record Number Setting' => '紀錄編號設定',
    'Remaining quota' => '尚餘名額',
    'Sales Date' => '@@銷售日期@@',
    'Sales End At' => '銷售結束日期',
    'Sales End Date' => '銷售結束日期',
    'Sales Start At' => '銷售開始日期',
    'Sales Start Date' => '銷售開始日期',
    'Sales Time' => '@@銷售日期@@',
    'Select Services Group' => '選擇服務組合',
    'Seq' => '',
    'Service' => '服務',
    'Service Apply Records' => '服務申請紀錄',
    'Service ID' => '',
    'Service Location' => '服務位置',
    'Service Qty' => '服務數量',
    'Service Schedule' => '服務日程',
    'Service Schedule ID' => '',
    'Service Schedule Service ID' => '',
    'Service Schedules' => '服務日程',
    'Service is not available.' => '服務未能提供。',
    'Services Group' => '服務組合',
    'Services Group ID' => '',
    'Services Groups' => '服務組合',
    'Small' => '小',
    'Sorry that this service cannot be apply! Please choose another service.' => '對不起，這項服務無法申請！ 請選擇其他服務。',
    'Template Services' => '廟宇服務',
    'Temple' => '廟宇',
    'Temples' => '廟宇',
    'Thank you. Your application #{num} has been received.' => '@@感謝您！我們已收到您的申請 #{num}。@@',
    'The number of periods of {service} that have been purchased has been exceeded.' => '已超過每張單訂可購買 {service} 的期數。',
    'The number of periods that have been purchased has been exceeded.' => '@@已超過每張單訂可購買的期數。@@',
    'Undefined' => '沒有',
    'User ID' => '',
    'Vertical' => '垂直',
    'Year For Record Number' => '紀錄編號的年份',
    '{qty,plural,=0{No quota} =1{Only one qouta} other{Only # quotas}} left.' => '只剩下 {qty} 個名額。',
    '每張申請只限一位善信' => '',
    '登記廟宇服務頁' => '',
    '確認後，此選項將<strong><u>不得作任何更改</u></strong>' => '',
];
