<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '聯絡地址',
    'Address: {0}' => '@@聯絡地址：{0}@@',
    'Contact' => '@@聯絡我們@@',
    'Contact Us' => '聯絡我們',
    'Detail' => '詳情',
    'Email' => '聯絡電郵',
    'Email: {0}' => '@@聯絡電郵：{0}@@',
    'Facebook' => '',
    'Fax' => '傳真號碼',
    'Font' => '@@字體@@',
    'Home' => '主頁',
    'Instagram' => '',
    'Latest Events' => '@@最新活動@@',
    'Member Login' => '@@會員登入@@',
    'Message' => '查詢內容',
    'Name' => '聯絡人',
    'Online Shop' => '網上購物',
    'Phone' => '聯絡電話',
    'Please fill in the form' => '或填寫以下表格',
    'Telephone: {0}' => '@@聯絡電話：{0}@@',
    'Temple Service' => '@@廟宇服務@@',
    'Thank you for your inquiry.' => '謝謝你的查詢。',
    'Website' => '聯絡網址',
    'WhatsApp' => '',
    'YouTube Channel' => '',
    '{0}:' => '{0}：',
];
