<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Dog' => '狗 (戌)',
    'Dragon' => '龍 (辰)',
    'Goat' => '羊 (未)',
    'Horse' => '馬 (午)',
    'Monkey' => '猴 (申)',
    'Ox' => '牛 (丑)',
    'Pig' => '豬 (亥)',
    'Rabbit' => '兔 (卯)',
    'Rat' => '鼠 (子)',
    'Rooster' => '雞 (酉)',
    'Snake' => '蛇 (巳)',
    'Tiger' => '虎 (寅)',
];
