<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%page_type2}}`.
 */
class m211106_212052_create_page_type2_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%page_type2}}', [
            'id'                     => $this->primaryKey(),
            'MID'                    => $this->integer()->unsigned(),
            'seq'                    => $this->integer(),
            'title_tw'               => $this->string(),
            'title_cn'               => $this->string(),
            'title_en'               => $this->string(),
            'content_tw'             => $this->getDb()->getSchema()->createColumnSchemaBuilder('longtext'),
            'content_cn'             => $this->getDb()->getSchema()->createColumnSchemaBuilder('longtext'),
            'content_en'             => $this->getDb()->getSchema()->createColumnSchemaBuilder('longtext'),
            'status'                 => $this->tinyInteger()->defaultValue(1),
            'created_at'             => $this->dateTime().' DEFAULT NOW()',
            'updated_at'             => $this->timestamp(),
            'updated_UID'            => $this->integer(),
        ]);

        $this->batchInsert('{{%page_type2}}', [
            'id',
            'MID',
            'seq',
            'title_tw',
            'title_cn',
            'title_en',
            'content_tw',
            'content_cn',
            'content_en',
            'status',
            'created_at',
            'updated_at',
            'updated_UID',
        ], [
            array('id' => '1','MID' => '12','seq' => '0','title_tw' => '','title_cn' => '','title_en' => 'Date','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">4 August 2023 (Friday) &ndash; 6 August 2023 (Sunday)</p>

            <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">The programme is at Hong Kong Time (UTC +8).&nbsp; You may check the time of your city at&nbsp;<a href="https://www.timeanddate.com/" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: transparent;" target="_blank">https://www.timeanddate.com/</a>.</p>
            ','status' => '1','created_at' => '2022-12-27 17:40:25','updated_at' => '2022-12-27 18:08:59','updated_UID' => '1'),
  array('id' => '2','MID' => '12','seq' => '1','title_tw' => '','title_cn' => '','title_en' => 'Conference Venue','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Hong Kong Convention &amp; Exhibition Centre (HKCEC)<br style="box-sizing: border-box;" />
            Address: 1 Expo Drive, Wanchai, Hong Kong</p>
            
            <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Framed by Hong Kong&rsquo;s skyline,&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">HKCEC</span>&nbsp;is a magnificent, multi-use venue located right in the heart of Hong Kong on its famous Victoria Harbour.</p>
            
            <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-weight: bolder;">Location and Transportation</span><br style="box-sizing: border-box;" />
            Participants can walk to the HKCEC from the MTR Exhibition Centre Station or from the MTR Wanchai Station; or Wanchai Ferry Pier within minutes. Please click&nbsp;<a href="https://www.hkcec.com/en/location-transportation" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: transparent;">here</a>&nbsp;for more suggested routes to go to the venue.</p>
            
            <p><iframe allowfullscreen="" height="450" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps/embed?hl=en&amp;pb=!1m18!1m12!1m3!1d3691.911533516342!2d114.17064761539821!3d22.281340749212408!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404015ea857b32b%3A0x462316dc9312d7d4!2z6aaZ5riv5pyD6K2w5bGV6Ka95Lit5b-D!5e0!3m2!1szh-TW!2shk!4v1666147966143!5m2!1szh-TW!2shk" style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255); border-width: 0px; border-style: initial;" width="100%"></iframe></p>
            ','status' => '1','created_at' => '2022-12-27 17:41:05','updated_at' => '2022-12-27 18:08:59','updated_UID' => '1'),
  array('id' => '3','MID' => '12','seq' => '2','title_tw' => '','title_cn' => '','title_en' => 'Official Language','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">The official language of the Conference is English.</span></p>
            ','status' => '1','created_at' => '2022-12-27 18:07:23','updated_at' => '2022-12-27 18:08:59','updated_UID' => '1'),
  array('id' => '4','MID' => '12','seq' => '3','title_tw' => '','title_cn' => '','title_en' => 'Accreditations','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">CME / CNE will be applied for local delegates of this Conference.&nbsp; Details of academic accreditation will be announced as soon as it becomes available.</span></p>
            ','status' => '1','created_at' => '2022-12-27 18:07:39','updated_at' => '2022-12-27 18:08:59','updated_UID' => '1'),
  array('id' => '5','MID' => '12','seq' => '4','title_tw' => '','title_cn' => '','title_en' => 'Certificate of Attendance','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Evaluation will be sent to all attendees after the Conference, on or before 11 August 2023. E-Certificate of attendance will be sent by email to those who filled out the Evaluation. If you do not receive the email by 11 August 2023, please check your junk mailbox or contact us at&nbsp;</span><a href="mailto:info@aoco2023hk.org" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;">info@aoco2023hk.org</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">.</span></p>
            ','status' => '1','created_at' => '2022-12-27 18:08:01','updated_at' => '2022-12-27 18:08:59','updated_UID' => '1'),
  array('id' => '6','MID' => '12','seq' => '5','title_tw' => '','title_cn' => '','title_en' => 'Disclaimer','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Whilst every attempt will be made to ensure that all aspects of the Conference announced will take place as scheduled, the Organizer reserves the right to make last minute changes should the need arise.</span></p>
            ','status' => '1','created_at' => '2022-12-27 18:08:18','updated_at' => '2022-12-27 18:08:59','updated_UID' => '1'),
  array('id' => '7','MID' => '12','seq' => '6','title_tw' => '','title_cn' => '','title_en' => 'Enquiry','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">AOCO 2023 Secretariat</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">c/o International Conference Consultants Ltd.</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Office address:</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Unit C-D, 17/F, Max Share Centre,</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">373 King&#39;s Road, North Point, Hong Kong</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Tel: (852) 2559 9973</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Fax: (852) 2547 9528</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Email:</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <a href="mailto:info@aoco2023hk.org" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;">info@aoco2023hk.org</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">&nbsp;(General / Registration Enquiry)</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <a href="mailto:program@aoco2023hk.org" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;">program@aoco2023hk.org</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">&nbsp;(Abstracts Enquiry)</span><br style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);" />
            <a href="mailto:sponsor@aoco2023hk.org" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;">sponsor@aoco2023hk.org</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">&nbsp;(Sponsorship Enquiry)</span></p>
            ','status' => '1','created_at' => '2022-12-27 18:08:38','updated_at' => '2022-12-27 18:08:59','updated_UID' => '1'),
  array('id' => '8','MID' => '6','seq' => '0','title_tw' => '','title_cn' => '','title_en' => 'Time Zone','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Hong Kong Time is eight hours ahead of Coordinated Universal Time (UTC +8).</span></p>
','status' => '1','created_at' => '2022-12-27 20:21:06','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '9','MID' => '6','seq' => '1','title_tw' => '','title_cn' => '','title_en' => 'Climate','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Hong Kong has a sub-tropical climate with seasonal changes. In August, average temperature is ranged from 26&deg;C to 31&deg;C. Please visit&nbsp;</span><a href="http://www.hko.gov.hk/" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;" target="_blank">Hong Kong Observatory</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">&nbsp;website for weather forecast before deciding what to pack.</span></p>
','status' => '1','created_at' => '2022-12-27 20:21:24','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '10','MID' => '6','seq' => '2','title_tw' => '','title_cn' => '','title_en' => 'Language','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">English and Cantonese are the official languages of Hong Kong. Most street signs, menus, tourist and government publications are usually bilingual in both English and Chinese. Most taxi drivers, salespersons, tourism industry employees are able to communicate in English.</span></p>
','status' => '1','created_at' => '2022-12-27 20:21:45','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '11','MID' => '6','seq' => '3','title_tw' => '','title_cn' => '','title_en' => 'Visa and Passport Requirements','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Visitors to Hong Kong must have valid passports. People of most countries do not require a visa to enter Hong Kong for tourism and can stay for periods varying from seven to 180 days, depending on their nationalities. Participants can check with the&nbsp;</span><a href="http://www.fmprc.gov.cn/mfa_eng/wjb_663304/zwjg_665342/2490_665344/" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;" target="_blank">Chinese embassy</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">&nbsp;in your country and the&nbsp;</span><a href="http://www.immd.gov.hk/eng/services/visas/visit-transit/visit-visa-entry-permit.html" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;" target="_blank">Department of the Government of the Hong Kong Special Administrative Region of the People&rsquo;s Republic of China</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">&nbsp; for details.</span></p>
','status' => '1','created_at' => '2022-12-27 20:22:09','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '12','MID' => '6','seq' => '4','title_tw' => '','title_cn' => '','title_en' => 'Travelling to Hong Kong','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Hong Kong is taking rigorous action in various areas to contain the spread of COVID-19. To learn more about the latest conditions imposed on inbound travellers and the latest developments about COVID-19 in Hong Kong, please visit&nbsp;</span><a href="http://www.coronavirus.gov.hk/" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;" target="_blank">www.coronavirus.gov.hk</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">.</span></p>
','status' => '1','created_at' => '2022-12-27 20:22:27','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '13','MID' => '6','seq' => '5','title_tw' => '','title_cn' => '','title_en' => 'Health and Safety','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Over 90% of population received 1st &amp; 2nd dose of vaccination while over 65% of population received 3rd dose of vaccination.</span></p>
','status' => '1','created_at' => '2022-12-27 20:22:51','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '14','MID' => '6','seq' => '6','title_tw' => '','title_cn' => '','title_en' => 'Hong Kong International Airport','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">For the information of the Hong Kong International Airport, please visit their website at&nbsp;<a href="http://www.hongkongairport.com/" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: transparent;" target="_blank">www.hongkongairport.com</a>&nbsp;.</p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);"><u style="box-sizing: border-box;"><span style="box-sizing: border-box; font-weight: bolder;">To and From the Airport</span></u><br style="box-sizing: border-box;" />
<span style="box-sizing: border-box; font-weight: bolder;"><em style="box-sizing: border-box;">Airport Express&nbsp;</em></span><br style="box-sizing: border-box;" />
The Airport Express is the fastest way to get between the city and the airport. It takes passengers to and from the Hong Kong Station in about 24 minutes. Train services are provided daily between 05:54 and 00:48 and at 10-minute intervals. Train tickets can be purchased at the Airport Express Customer Service Centre located in the Arrivals Hall of the Hong Kong International Airport.&nbsp;<br style="box-sizing: border-box;" />
For details. Please visit&nbsp;<a href="http://www.mtr.com.hk/en/customer/services/airport_express_index_tourist.html" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: transparent;" target="_blank">http://www.mtr.com.hk/en/customer/services/airport_express_index_tourist.html</a>.<br style="box-sizing: border-box;" />
<br style="box-sizing: border-box;" />
<span style="box-sizing: border-box; font-weight: bolder;"><em style="box-sizing: border-box;">Taxi</em></span><br style="box-sizing: border-box;" />
Taxis offer a flexible way to and from the airport. Arriving passengers can pick up a taxi at the Taxi Station outside the Arrivals Hall. Taxis in Hong Kong are colour-coded according to their operating areas. Urban taxis are red. The current rates are HKD27 on flag fall for the first 2 kilometres plus HKD1.9 every further 0.2 kilometre. The charge will be changed to HKD1.3 per 0.2 kilometre&nbsp;after the chargeable amount has reached HKD93.5. Additional charges for luggage and tolls apply.</p>
','status' => '1','created_at' => '2022-12-27 20:23:18','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '15','MID' => '6','seq' => '7','title_tw' => '','title_cn' => '','title_en' => 'Public Transportation','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Hong Kong is so compact that getting around is quick and easy.&nbsp; An efficient public transport system &ndash; network of urban trains (Mass Transit Railway or MTR) and numerous routes of trams, buses, ferries and also taxi &ndash; enable visitors to explore Hong Kong conveniently and safely on their own.&nbsp; Tourist MTR 1-Day Pass is tailored for tourist travel around Hong Kong.&nbsp; Tourists can have any one day of unlimited rides on the MTR (except the Airport Express Line) within the ticket validity period. For details, please visit&nbsp;<a href="http://www.mtr.com.hk/en/customer/tickets/day_pass_tourist.html" style="box-sizing: border-box; color: rgb(52, 152, 219); text-decoration-line: none; background-color: transparent;" target="_blank">http://www.mtr.com.hk/en/customer/tickets/day_pass_tourist.html</a></p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">An octopus card which will allow travel on all forms of public transport (including the Star Ferry and Trams) can be purchased at MTR Service Centre.</p>
','status' => '1','created_at' => '2022-12-27 20:23:40','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '16','MID' => '6','seq' => '8','title_tw' => '','title_cn' => '','title_en' => 'Currency and Credit Card','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">The official currency of Hong Kong is the Hong Kong Dollar (HKD). One US Dollar is approximately HKD 7.8. Participants can change your currency for HKD at any authorized money exchanger or bank. Major banks open from 9 am to 4: pm on Monday to Friday, and 9 am to 12 pm on Saturday. Automatic Teller Machines (ATM) can be found almost everywhere and provide 24-hour cash withdrawal for HKD.</p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">International credit cards such as VISA, MasterCard, Diners Club, UnionPay and American Express are commonly accepted by hotels, retail shops and restaurants in Hong Kong. Such premises usually display stickers showing the credit cards they accept at their entrances.</p>
','status' => '1','created_at' => '2022-12-27 20:23:58','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '17','MID' => '6','seq' => '9','title_tw' => '','title_cn' => '','title_en' => 'Electricity','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;">The standard voltage in Hong Kong is 220 volts AC/50 cycles.&nbsp; The plug/socket system in Hong Kong is a three-pronged UK-style plug.<img alt="electricity" height="64" src="https://aoco2023hk.org/images/abouthk01.jpg" style="box-sizing: border-box; vertical-align: middle; border-style: none; float: right;" width="150" /></p>
','status' => '1','created_at' => '2022-12-27 20:24:18','updated_at' => '2022-12-27 20:28:20','updated_UID' => '1'),
  array('id' => '18','MID' => '6','seq' => '10','title_tw' => '','title_cn' => '','title_en' => 'Telecommunication','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Local SIM cards can be purchased at round-the-clock convenience stores. Participants may also consider buying a local SIM card at the Arrival Hall of the Hong Kong International Airport upon landing. International Direct Dial (IDD) service to most countries and regions of the world is available at most hotels for a fee.</span></p>
','status' => '1','created_at' => '2022-12-27 20:24:46','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '19','MID' => '6','seq' => '11','title_tw' => '','title_cn' => '','title_en' => 'Smoking Policy','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">Smoking is prohibited in all indoor public places in Hong Kong, including restaurants, bars and malls. Any person smoking or carrying a lighted cigarette, cigar, or pipe in a no-smoking area will be liable to a fixed penalty of HKD 1,500.</span></p>
','status' => '1','created_at' => '2022-12-27 20:25:02','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '20','MID' => '6','seq' => '12','title_tw' => '','title_cn' => '','title_en' => 'Sales Tax','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">There is no sales tax on goods and services in Hong Kong.</span></p>
','status' => '1','created_at' => '2022-12-27 20:25:18','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1'),
  array('id' => '21','MID' => '6','seq' => '13','title_tw' => '','title_cn' => '','title_en' => 'Getting Around Hong Kong','content_tw' => NULL,'content_cn' => NULL,'content_en' => '<p><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">For the most up-to-date tourist information, please visit the website of the Hong Kong Tourism Board at&nbsp;</span><a href="http://www.discoverhongkong.com/" style="box-sizing: border-box; color: rgb(95, 174, 227); text-decoration-line: none; background-color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px;" target="_blank">www.discoverhongkong.com</a><span style="color: rgb(68, 68, 68); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 17.6px; background-color: rgb(255, 255, 255);">.</span></p>
','status' => '1','created_at' => '2022-12-27 20:25:41','updated_at' => '2022-12-27 20:26:06','updated_UID' => '1')
        ]);        
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%page_type2}}');
    }
}
