<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Booking' => '',
    'Booking Name' => '',
    'Create Level' => '新增级别',
    'Level' => '级别',
    'Registration Confirmation' => '登记确认',
    'Template File' => '',
    '不需要' => '不需要',
    '功德狀' => '功德状',
    '受薦先人稱呼及姓名' => '受荐先人称呼及姓名',
    '只能包含 A-Z、a-z、0-9、-及_。' => '只能包含 A-Z、a-z、0-9、-及_。',
    '善信芳名' => '善信芳名',
    '善信電話' => '善信电话',
    '抱歉！暫未能預約。' => '抱歉！暂未能预约。',
    '新增服務登記表格' => '新增服务登记表格',
    '服務登記紀錄' => '服务登记纪录',
    '服務登記表格' => '服务登记表格',
    '正號附薦包' => '正号附荐包',
    '登記完成時間' => '登记完成时间',
    '登記時間' => '登记时间',
    '登記確認時間' => '登记确认时间',
    '登記結束日期' => '登记结束日期',
    '登記編號' => '登记编号',
    '登記開始日期' => '登记开始日期',
    '籍貫(1)' => '籍贯(1)',
    '籍貫(2)' => '籍贯(2)',
    '網址' => '网址',
    '聯絡地址' => '联络地址',
    '聯絡電郵' => '联络电邮',
    '附薦位級別' => '附荐位级别',
    '附薦位級別 未能預約。' => '附荐位级别 未能预约。',
    '附送正號附薦包／功德狀' => '附送正号附荐包／功德状',
    '陽居敬奉人姓名' => '阳居敬奉人姓名',
    '需要' => '需要',
    '預約將於 {datetime} 開始。' => '预约将於 {datetime} 开始。',
    '預約已於 {datetime} 結束。' => '预约已於 {datetime} 结束。',
    '額外功德狀' => '额外功德状',
    '額外功德狀價錢' => '额外功德状价钱',
    '額外大號附薦包' => '额外大号附荐包',
    '額外大號附薦包價錢' => '额外大号附荐包价钱',
    '額外正號附薦包' => '额外正号附荐包',
    '{qty,plural,=0{No quota} =1{Only one qouta} other{Only # quotas}} left.' => '只剩下 {qty} 个名额。',
];
