<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '启用',
    'Member' => '会员',
    'Super Admin' => '超级管理员',
    'Admin' => '管理员',
    'Allow' => '允许',
    'Blog' => 'Blog',
    'Can' => '可以',
    'Cannot' => '不可以',
    'Deactivate' => '停用',
    'Disabled' => '停用',
    'Enabled' => '启用',
    'File List' => '档案列表',
    'Link' => '连结',
    'Menu Level1' => '第一层',
    'Menu Level2' => '第二层',
    'No' => '否',
    'Not Allowed' => '不允许',
    'Page' => '页',
    'User' => '普通用户',
    'Yes' => '是',
    'Checkout done' => '已完成结账',
    'Checkout form submitted' => '已完成结账订单',
    'Checkout processing' => '结账处理中',
    'Checkout submitted' => '结账已提交',
    'Order submitted' => '已提交订单',
    'Payment processing' => '付款处理中',
    'Shipped' => '已发货',
    'Shopping' => '购物中',
    'To be shipped' => '待送货',
    'Confirmed' => '已确认',
    'Credit cart payment failed' => '信用卡付款失败',
    'Credit cart payment processing' => '信用卡付款处理中',
    'Finish' => '已完成',
    'Canceled' => '已取消',
    'In delivery' => '送货中',
    'Waiting for confirmation' => '待确认',
    'Waiting for Direct Bank-in' => '等候银行入数',
    'Waiting for Direct Bank-in confirmation' => '等候银行入数确认',
];
