<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Remaining quota' => '尚馀名额',
    'Template Services' => '庙宇服务',
    'Service Schedule' => '服务日程',
    'Service Schedules' => '服务日程',
    'Services Group' => '服务组合',
    'Services Groups' => '服务组合',
    'Service Location' => '服务位置',
    'Default Qty' => '预设数量',
    'Service Qty' => '服务数量',
    'Sales Start At' => '销售开始日期',
    'Sales End At' => '销售结束日期',
    'Sales Time' => '销售日期',
    'Sales Date' => '销售日期',
    'Temple' => '庙宇',
    'Temples' => '庙宇',
    'Service' => '服务',
    'Date' => '日期',
    'Price' => '价钱',
    'Apply' => '申请',
    'Blessing Card' => '祈福卡',
    'Download Blessing Card' => '下载祈福卡',
    'Blessing Message' => '祈福字句',
    'Blessing Message Font Size' => '祈福字句文字大小',
    'Blessing Message Text Orientation' => '祈福字句方向',
    'Date of Application' => '申请日期',
    'No.' => '编号',
    'Record Num' => '纪录编号',
    'Thank you. Your application #{num} has been received.' => '感谢您！我们已收到您的申请 #{num}。',
    'Sorry that this service cannot be apply! Please choose another service.' => '对不起，这项服务无法申请！ 请选择其他服务。',
    'Service is not available.' => '服务未能提供。',
    'The number of periods that have been purchased has been exceeded.' => '已超过每张单订可购买的期数。',
    'The number of periods of {service} that have been purchased has been exceeded.' => '已超过每张单订可购买 {service} 的期数。',
    'Full' => '额满',
    'Message Card Config' => '字句卡设定',
    'Undefined' => '没有',
    'Small' => '小',
    'Middle' => '中',
    'Large' => '大',
    'Select Services Group' => '选择服务组合',
    'Create Temple' => '新增庙宇',
    'Create Service' => '新增服务',
    'Create Services Group' => '新增服务组合',
    'Create Service Schedule' => '新增服务日程',
    'Service Apply Records' => '服务申请纪录',
    'Horizontal' => '横行',
    'Vertical' => '垂直',
    'Maximin Number Of Periods Per Order' => '每次订单最多购买期数',
    'Number Of Periods' => '占期数',
    '{qty,plural,=0{No quota} =1{Only one qouta} other{Only # quotas}} left.' => '只剩下 {qty} 个名额。',
    'Duplicate record number setting.' => '重複的纪录编号设定',
    'Record Number Setting' => '纪录编号设定',
    'Year For Record Number' => '纪录编号的年份',
    'Period For Record Number' => '纪录编号的期数',
    'Record Confirmed Time' => '纪录确认时间',
    'Record Completed Time' => '纪录完成时间',
    "Name: \nZodiac: \nAddress District: " => "姓名：\n生肖：\n住址地区：",
    'Please input Name, Zodiac and Address District' => '请输入姓名、生肖及住址地区',
];
