<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '一仟八佰萬' => '',
    '一億二仟萬' => '',
    '一億八仟萬' => '',
    '一億六仟萬' => '',
    '三仟八佰萬' => '',
    '三億八仟萬' => '',
    '上環列聖宮' => '',
    '不限' => '',
    '不需要' => '',
    '九仟萬' => '',
    '二億二仟萬' => '',
    '二億八仟萬' => '',
    '代善信借庫' => '',
    '代善信借庫價錢' => '',
    '代善信借庫摸庫完結時間' => '',
    '代善信借庫摸庫時間' => '',
    '代善信借庫摸庫類型' => '',
    '代善信借庫數量' => '',
    '代善信還庫' => '',
    '代善信還庫價錢' => '',
    '代善信還庫數量' => '',
    '八仟八佰萬' => '',
    '八仟萬' => '',
    '八億八仟萬' => '',
    '六仟萬' => '',
    '善信芳名' => '',
    '山東街水月宮' => '',
    '已摸庫（副）' => '',
    '已摸庫（正）' => '',
    '已滿額。' => '',
    '恭喜摸得庫銀 {0}！' => '',
    '慈雲山觀音佛堂' => '',
    '我的開庫申請' => '',
    '抱歉！暫未能申請。' => '',
    '摸庫將於 {datetime} 開始。' => '',
    '摸得庫銀' => '',
    '摸得庫銀（副）' => '',
    '摸得庫銀（正）' => '',
    '新增觀音開庫' => '',
    '沒有提供借庫申請。' => '',
    '沒有提供還庫申請。' => '',
    '申請完成時間' => '',
    '申請將於 {datetime} 開始。' => '',
    '申請已於 {datetime} 結束。' => '',
    '申請時間' => '',
    '申請確認時間' => '',
    '申請結束日期' => '',
    '申請開始日期' => '',
    '空白為不提供借庫服務。' => '',
    '空白為不提供還庫服務。' => '',
    '空白為不限制數量。' => '',
    '觀音開庫' => '',
    '觀音開庫申請紀錄' => '',
    '設置 利是數量 及 庫銀機率。' => '',
    '還有 %s 封開庫利是未開啟' => '',
    '開庫名稱' => '',
    '需要' => '',
    '需要福物' => '',
    '（副）' => '',
    '（正）' => '',
];
